{% set name = "rednose" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6da77917788be277b70259edc0bb92fc6f28fe268b765b4ea88206cc3543a3e1


build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - setuptools
    - python-termstyle >=0.1.7
    - colorama

test:
  imports:
    - test_files
  commands:
    - pip check
  requires:
    - six ==1.10.0
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JBKahn/rednose
  license_file: LICENSE
  license: MIT
  summary: 'coloured output for nosetests'
  license_family: MIT
  dev_url: https://github.com/JBKahn/rednose

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
