{% set name = "rednose" %}
{% set version = "1.3.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "6da77917788be277b70259edc0bb92fc6f28fe268b765b4ea88206cc3543a3e1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}


build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - setuptools
    - python-termstyle >=0.1.7
    - colorama

test:
  imports:
    - test_files

  requires:
    - six ==1.10.0

about:
  home: https://github.com/JBKahn/rednose
  license_file: LICENSE
  license: MIT
  summary: 'pretty output formatter for python-nosetests'
  license_family: MIT
  dev_url: https://github.com/JBKahn/rednose

extra:
  recipe-maintainers:
    - pmlandwehr
